# Generated by Django 3.1.4 on 2020-12-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('badgeID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('classification', models.CharField(max_length=50, null=True)),
                ('allegation', models.CharField(max_length=50, null=True)),
                ('finding', models.CharField(max_length=50, null=True)),
                ('badgeID_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.officer')),
            ],
        ),
    ]
