# Generated by Django 3.1.4 on 2020-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy', models.CharField(max_length=50)),
                ('badgeID', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('allegation', models.CharField(max_length=20)),
                ('finding', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='officer',
            name='badgeID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='firstName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='lastName',
            field=models.CharField(max_length=20),
        ),
    ]
